/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.GridLayout;
import java.awt.event.ActionListener;
import javax.swing.JButton;

/**
 *
 * @author Gabriel
 */
public class VistaTablero extends javax.swing.JFrame {

   ///////atributos/////////////////////
    public JButton[][] matrizVista; //matriz de botones
 
////////Constructor////////////////    
    public VistaTablero() {
        initComponents();
        crearEscenario();
        //this.setPreferredSize(new Dimension(800,700));
    }
     public JButton[][] getCoordenadas() {
        return matrizVista;
    }

    public void setCoordenadas(JButton[][] coordenadas) {
        this.matrizVista = coordenadas;
    }
    
    public JButton[][] crearEscenario(){
       jPanel1.setLayout(new GridLayout(25,25)); //se le da forma de matriz al panel 
       jPanel1.setPreferredSize(new Dimension(600, 600));
        matrizVista = new JButton[25][25]; //se crea un arreglo de arreglo de botones de 25x25
        for(int i = 0; i<25;i++){
            for(int j = 0; j<25; j++){
                matrizVista[i][j] = new JButton(); //Se instancian coordenadas
                jPanel1.add(matrizVista[i][j]); //Se agregan botones al panel
                matrizVista[i][j].setPreferredSize(new Dimension(25, 25));
                
            }
        }
    return matrizVista;
    }
    
    
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(900, 700));
        setPreferredSize(new java.awt.Dimension(900, 700));
        setResizable(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 501, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 442, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 234, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 166, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

public void agregarListener(ActionListener al){ //metodo que escucha botones
    for(int i= 0; i<25; i++){
        for(int j= 0; j<25;j++){
            matrizVista[i][j].setFocusPainted(true);
            matrizVista[i][j].addActionListener(al); //escucha a todos los botones de la matriz
            matrizVista[i][j].setOpaque(true);
        }
    }
}

}














